<?php
/** 
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/**
 * @var $block \Manadev\LayeredNavigation\Blocks\Navigation
 *
 * Based on app/code/Magento/LayeredNavigation/view/frontend/templates/layer/view.phtml (diff to check
 * what has changed).
 */
?>

<?php if ($block->isVisible()): ?>
    <div class="block filter mana-filter-block">
        <div class="block-title filter-title">
            <strong><?php echo __('Shop By') ?></strong>
        </div>

        <div class="block-content filter-content">
            <?php if ($block->hasState() && $block->isAppliedFilterVisible()) : ?>
                <div class="filter-current">
                    <strong class="block-subtitle filter-current-subtitle" role="heading" aria-level="2" data-count="<?php echo $block->getAppliedOptionCount() ?>"><?php echo __('Now Shopping by') ?></strong>
                    <ol class="items">
                        <?php foreach ($block->getAppliedFilters() as $engineFilter): ?>
                            <?php foreach ($engineFilter->getAppliedItems() as $item) : ?>
                                <li class="item"><?php echo $block->renderAppliedItem($engineFilter, $item) ?></li>
                            <?php endforeach; ?>
                        <?php endforeach; ?>
                    </ol>
                </div>

                <div class="block-actions filter-actions">
                    <a href="<?php echo $block->getClearUrl() ?>" class="action clear filter-clear"><span><?php echo __('Clear All') ?></span></a>
                </div>
            <?php endif; ?>

            <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?php echo __('Shopping Options') ?></strong>

            <dl class="filter-options" id="narrow-by-list">
            <?php foreach ($block->getFilters() as $filter): ?>
                <?php $cssClass = $block->getData('css_prefix') . '-filter-' . str_replace('_', '-', $filter->getFilter()->getData('param_name')) ?>
                <dt role="heading" aria-level="3" class="filter-options-title <?php echo $cssClass ?>"><?php echo $block->escapeHtml(__($filter->getName())) ?></dt>
                <dd class="filter-options-content <?php echo $cssClass ?>"><?php echo $block->renderFilter($filter) ?></dd>
            <?php endforeach; ?>
            </dl>
        </div>
    </div>
<?php endif; ?>
