<div class="container">
	<div class="row">

		<div class="col-xs-12 col-sm-12">
			<legend class="legend"><span>Notifications</span></legend>
			<ul class="tabs">
				<li class="tab-link current" role="tab"  data-tab="tab-1">Webinars</li>
				<li class="tab-link" role="tab"  data-tab="tab-2">Dues Renewal</li>
				<li class="tab-link" role="tab" data-tab="tab-3">Annual Update</li>
				<li class="tab-link" role="tab" data-tab="tab-4">New Courses</li>
			</ul>
			<div id="tab-1" class="tab-content current" role="tabpanel">
				<p>Nam rutrum vitae nisl sed fringilla. Nulla fringilla non dolor eu maximus. Fusce sed nisi pulvinar purus sodales condimentum nec sit amet ante. Nullam ac mauris turpis. Donec vel condimentum neque. Nunc diam quam, rutrum nec aliquet id, congue non arcu.</p>			
				<div id="collapseOne" class="panel-collapse in panel-body">	 
					
					<div class="center-this-container">
						<a href="#divForm" id="btnForm"class="main-button blue-button">Notify Me of Upcoming Webinars</a>
					     <div id ="divForm" style="display:none;">
					 
							<div id="dialogContent">
								 <form action = "" method ="post" class="padding15">
								 
								  <div class="field form-group row">
									  <label class="label col-md-3">When</label>
									  <div class="control col-md-9">
										 <select class="">
											<option value="30">30 Days</option>
											<option value="60">60 Days</option>
											<option value="90">90 Days</option>
										  </select>
									</div>
								  </div>
								<div class="field form-group row">
									 <label class="label col-md-3">How</label>
									  <div class="control col-md-9">
										  <input type="radio" name="when_notity" value="text" checked> Text
										  <input type="radio" name="when_notity" value="email"> Email
									</div>
								  </div>
								<div class="buttons">
									 <input type="submit" value="submit" class ="notification btn primary action capitalize">
								</div>
								 </form> 
							</div>

					    </div>
					</div>
				</div>
			</div>
			<div id="tab-2" class="tab-content" role="tabpanel" >
				 <p>Your CIC dues will be up for renewal on January 30, 2017.</p>
				 <div class="pulled-text">
					<p>This text is in a separate div that will be pulled from elsewhere</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus et diam congue urna euismod mattis. Vestibulum pulvinar risus viverra augue tristique lobortis. Aliquam quis rhoncus libero. Nam aliquet dictum lorem ac faucibus. Proin scelerisque condimentum neque, non egestas sem scelerisque at. Nam volutpat dolor eget felis sagittis tempus. Nunc quis purus scelerisque, ultricies metus in, tristique ex. Maecenas vestibulum diam nec laoreet volutpat. Curabitur maximus arcu sit amet enim viverra porttitor. Suspendisse turpis lorem, egestas quis justo vel, commodo placerat dolor. Vivamus mollis dolor eros, non commodo dolor pharetra eget. Sed ac purus blandit, dignissim est non, vestibulum est. Praesent vehicula facilisis turpis. Suspendisse potenti. Sed eleifend dignissim augue egestas ornare.</p>
					<p>Etiam imperdiet risus id fringilla rutrum. Morbi posuere orci quis libero eleifend, ut rhoncus purus tempus. Aenean auctor posuere massa a sagittis. Aliquam aliquet diam quis vulputate rhoncus. Pellentesque non elit diam. Mauris pharetra interdum viverra. Aenean et sodales leo, sit amet auctor lorem. Donec aliquet massa eu est tristique varius. Duis ut venenatis dui, in aliquam tellus. Ut non eleifend nunc. Nullam aliquet libero id turpis blandit, vel aliquet felis ullamcorper. Phasellus fermentum risus id magna laoreet, eget semper arcu fermentum.</p>
				</div>
				 <div class="center-this-container">
					<a href="#" class="main-button blue-button">Pay Dues Now</a>
					<a href="#duesNotify" id="duesNotification"class="main-button blue-button">Remind Me</a>
				</div>
			</div>
			<div id="tab-3" class="tab-content" role="tabpanel" >
				<p>Your annual update is upcoming on January 30, 2017.</p>
				<div class="pulled-text">
					<p>This text is in a separate div that will be pulled from elsewhere</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus et diam congue urna euismod mattis. Vestibulum pulvinar risus viverra augue tristique lobortis. Aliquam quis rhoncus libero. Nam aliquet dictum lorem ac faucibus. Proin scelerisque condimentum neque, non egestas sem scelerisque at. Nam volutpat dolor eget felis sagittis tempus. Nunc quis purus scelerisque, ultricies metus in, tristique ex. Maecenas vestibulum diam nec laoreet volutpat. Curabitur maximus arcu sit amet enim viverra porttitor. Suspendisse turpis lorem, egestas quis justo vel, commodo placerat dolor. Vivamus mollis dolor eros, non commodo dolor pharetra eget. Sed ac purus blandit, dignissim est non, vestibulum est. Praesent vehicula facilisis turpis. Suspendisse potenti. Sed eleifend dignissim augue egestas ornare.</p>
					<p>Etiam imperdiet risus id fringilla rutrum. Morbi posuere orci quis libero eleifend, ut rhoncus purus tempus. Aenean auctor posuere massa a sagittis. Aliquam aliquet diam quis vulputate rhoncus. Pellentesque non elit diam. Mauris pharetra interdum viverra. Aenean et sodales leo, sit amet auctor lorem. Donec aliquet massa eu est tristique varius. Duis ut venenatis dui, in aliquam tellus. Ut non eleifend nunc. Nullam aliquet libero id turpis blandit, vel aliquet felis ullamcorper. Phasellus fermentum risus id magna laoreet, eget semper arcu fermentum.</p>
				</div>
				 <div class="center-this-container">
					<a href="#" class="main-button blue-button">Search for Courses</a>
					<a href="#duesNotify" id="duesNotification"class="main-button blue-button">Remind Me</a>
					     <div id ="duesNotify" style="display:none;">
					 
							<div id="dialogContent">
								 <form action = "" method ="post" class="padding15">
								 
								  <div class="field form-group row">
									  <label class="label col-md-3">When</label>
									  <div class="control col-md-9">
										 <select class="">
											<option value="30">30 Days</option>
											<option value="60">60 Days</option>
											<option value="90">90 Days</option>
										  </select>
									</div>
								  </div>
								<div class="field form-group row">
									 <label class="label col-md-3">How</label>
									  <div class="control col-md-9">
										  <input type="radio" name="when_notity" value="text" checked> Text
										  <input type="radio" name="when_notity" value="email"> Email
									</div>
								  </div>
								<div class="buttons">
									 <input type="submit" value="submit" class ="notification btn primary action capitalize">
								</div>
								 </form> 
							</div>

					    </div>
					
					
					
					
				</div>
			</div>
			<div id="tab-4" class="tab-content" role="tabpanel" >
				<p>Nam rutrum vitae nisl sed fringilla. Nulla fringilla non dolor eu maximus. Fusce sed nisi pulvinar purus sodales condimentum nec sit amet ante. Nullam ac mauris turpis. Donec vel condimentum neque. Nunc diam quam, rutrum nec aliquet id, congue non arcu.</p>
			</div>
		</div>
	</div><!-- Row -->
</div><!-- Container -->
<script type="text/javascript">
        requirejs(['jquery','jquery/ui','vesbaseFancybox'],
        function ($) {
            $(document).ready(function() {
				$("#btnForm").fancybox();
				$("#duesNotification").fancybox();
				
                $('ul.tabs li').click(function(){
                    var tab_id = $(this).attr('data-tab');

                    $('ul.tabs li').removeClass('current');
                    $('.tab-content').removeClass('current');

                    $(this).addClass('current');
                    $("#"+tab_id).addClass('current');
                });
			});
        });
</script>