<?php
/**
 * @var $block \Magenest\Salesforce\Block\Adminhtml\CustomerEdit\Tab\View\SalesforceCustomerInfo
 */
$syncHistory = $block->getSyncLog();
?>

<div class="fieldset-wrapper customer-information">
    <div class="fieldset-wrapper-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Information') ?></span>
    </div>
    <table class="admin__table-secondary">
        <tbody>
        <?php echo $block->getChildHtml(); ?>
        <tr>
            <th><?php /* @escapeNotVerified */ echo __('Salesforce Contact ID:') ?></th>
            <td><a target="_blank" href="<?php echo $block->getSalesforceUrl('Contact')?>"><?php /* @escapeNotVerified */ echo $block->getSalesforceId('Contact') ?></a></td>
        </tr>
        <tr>
            <th><?php /* @escapeNotVerified */ echo __('Salesforce Lead ID:') ?></th>
            <td><a target="_blank" href="<?php echo $block->getSalesforceUrl('Lead')?>"><?php /* @escapeNotVerified */ echo $block->getSalesforceId('Lead') ?></a></td>
        </tr>
        <tr>
            <th><?php /* @escapeNotVerified */ echo __('Salesforce Account ID:') ?></th>
            <td><a target="_blank" href="<?php echo $block->getSalesforceUrl('Account')?>"><?php /* @escapeNotVerified */ echo $block->getSalesforceId('Account') ?></a></td>
        </tr>
        <tr>
            <th><?php /* @escapeNotVerified */ echo __('Last Updated At:') ?></th>
            <td><?php /* @escapeNotVerified */ echo $block->getLastUpdatedAt() ?></td>
        </tr>
        <tr>
            <th><?php /* @escapeNotVerified */ echo __('Created At:') ?></th>
            <td><?php /* @escapeNotVerified */ echo $block->getCreatedAt() ?></td>
        </tr>
        <tr>
            <th><?php /* @escapeNotVerified */ echo __('Sync Contact:') ?></th>
            <td><button onclick="location.href='<?php echo $block->getSyncButtonUrl('Contact') ?>'">Sync to Contact Now</button></td>
        </tr>
        <tr>
            <th><?php /* @escapeNotVerified */ echo __('Sync Lead:') ?></th>
            <td><button onclick="location.href='<?php echo $block->getSyncButtonUrl('Lead') ?>'">Sync to Lead Now</button></td>
        </tr>
        <tr>
            <th><?php /* @escapeNotVerified */ echo __('Sync Account:') ?></th>
            <td><button onclick="location.href='<?php echo $block->getSyncButtonUrl('Account') ?>'">Sync to Account Now</button></td>
        </tr>
        </tbody>
    </table>
</div>
<br/><br/><br/>
<div class="fieldset-wrapper customer-information">
    <div class="fieldset-wrapper-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Sync History') ?></span>
    </div>
    <table class="admin__table-secondary">
        <tbody>
        <?php echo $block->getChildHtml(); ?>
        <?php if ($syncHistory): ?>
            <?php $count = 1 ?>
            <?php foreach ($syncHistory as $v): ?>
                <tr>
                    <th><? echo $count.'.' ?></th>
                    <td><span style="font-size:12pt"><?php /* @escapeNotVerified */ echo $v->getData('datetime') ?></span></td>
                    <td><span style="font-size:12pt"><?php /* @escapeNotVerified */ echo $v->getData('salesforce_table') ?></span></td>
                    <td><?php if ($v->getData('status') == 1) echo __('Ok'); else echo __('Failed'); ?></td>
                    <?php $count++ ?>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </table>
</div>
