<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/* @var $block \Manadev\Core\Blocks\Adminhtml\FieldRenderer */
$element = $block->getElement();
$note = $element->getNote() ? '<div class="note" id="' . $element->getId() . '-note">' . $element->getNote() . '</div>' : '';
$elementBeforeLabel = $element->getExtType() == 'checkbox admin__control-checkbox' || $element->getExtType() == 'radio admin__control-radio';
$addOn = ($element->getBeforeElementHtml() || $element->getAfterElementHtml()) && !$element->getNoWrapAsAddon();
$fieldId = ($element->getHtmlContainerId()) ? ' id="' . $element->getHtmlContainerId() . '"' : '';
$fieldClass = "manadev-admin-field admin__field field field-{$element->getId()} {$element->getCssClass()}";
$fieldClass .= ($elementBeforeLabel) ? ' choice' : '';
$fieldClass .= ($addOn) ? ' with-addon' : '';
$fieldClass .= ($element->getRequired()) ? ' required _required' : '';
$fieldClass .= ($note) ? ' with-note' : '';
$fieldClass .= (!$element->getLabelHtml()) ? ' no-label' : '';

$useDefaultLabel = $block->getUseDefaultLabel();
$manadevFieldSettings = [];
if ($useDefaultLabel) {
    $manadevFieldSettings['hasDefault'] = true;
}
if ($element->hasData('default')) {
    $manadevFieldSettings['defaultValue'] = $element->getData('default');
}

$fieldAttributes = $fieldId . ' class="' . $fieldClass . '" '
    . $block->getUiId('form-field', $element->getId())
    . ' data-mage-init=\'{ "manadevField": '. json_encode($manadevFieldSettings)  .'}\''
    . ($element->getFieldExtraAttributes() ? ' ' . $element->getFieldExtraAttributes() : '');

?>

<?php if (!$element->getNoDisplay()): ?>
    <?php if ($element->getType() == 'hidden'): ?>
        <?php echo $element->getElementHtml() ?>
    <?php else: ?>
    <div<?php /* @escapeNotVerified */ echo $fieldAttributes ?>>
        <?php if ($elementBeforeLabel): ?>
            <?php echo $element->getElementHtml() ?>
            <?php echo $element->getLabelHtml() ?>
            <?php /* @escapeNotVerified */ echo $note ?>
        <?php else: ?>
            <?php echo $element->getLabelHtml() ?>
            <div class="admin__field-control control">
                <?php /* @escapeNotVerified */ echo($addOn) ? '<div class="admin__field">' . $element->getElementHtml() . '</div>' : $element->getElementHtml(); ?>
                <?php /* @escapeNotVerified */ echo $note ?>
            </div>
        <?php endif; ?>
        <?php if ($element->getScopeLabel()): ?>
            <div class="field-service" value-scope="<?php /* @escapeNotVerified */ echo $element->getScopeLabel()?>">
            </div>
        <?php endif;?>
        <?php if ($useDefaultLabel) : ?>
            <div class="field-service">
                <label for="<?php echo $element->getHtmlId() ?>_default" class="choice use-default">
                    <input <?php if ($element->getReadonly()):?> disabled="disabled"<?php endif; ?>
                        type="checkbox"
                        name="use_default[]"
                        class="use-default-control"
                        id="<?php echo $element->getHtmlId() ?>_default"
                        <?php if ($block->getUseDefaultValue()): ?> checked="checked"<?php endif; ?>
                        value="<?php echo $element->getName() ?>"/>
                    <span class="use-default-label"><?php echo $useDefaultLabel ?></span>
                </label>
            </div>
        <?php endif ?>
    </div>
    <?php endif; ?>
<?php endif; ?>
