<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @var $block \Magento\Backend\Block\Widget\Grid\Serializer
 */
?>
<?php $_id = 'id_' . md5(microtime()) ?>
<?php $formId = $block->getFormId()?>
<?php $gridId = $block->getGridId() ?>
<script>
    require([
        'Manadev_Core/js/featureGridSerializer',
        'jquery',
        'prototype',
        'mage/adminhtml/grid'
    ], function(featureGridSerializer, $){
        var loadSerializer = function () {
            if(window.manaSerializerLoaded !== true) {
                window.manaSerializerLoaded = true;
                var serializeInput = document.createElement('input');
                serializeInput.type = 'hidden';
                serializeInput.name = '<?php echo $block->getInputElementName()?>';
                serializeInput.id = '<?php echo $_id?>';
                try {
                    document.getElementById('<?php echo $formId?>').appendChild(serializeInput);
                    document.getElementById('<?php echo $formId?>').appendChild(document.getElementById('<?php echo $gridId ?>'));
                    new featureGridSerializer('<?php echo $_id?>', <?php echo $block->getDataAsJSON() ?>, <?php echo $block->getColumnInputNames(true) ?>, <?php echo $block->getGridBlock()->getJsObjectName() ?>, '<?php echo $block->getReloadParamName()?>');
                } catch(e) {
                    //Error add serializer
                }
            }
        };
        Event.observe(window, "load", loadSerializer);
        // Workaround on unknown issue that `Event.observe` event does not fire.
        $(loadSerializer);
    });
</script>
