SELECT C.CLI_USERNAME USERNAME,
      C.CLI_PASSWORD PASSWORD,
      C.CLI_GENDER GENDER,
      C.CLI_PREFIX PREFIX,
      C.CLI_FIRST_NAME FIRSTNAME,
      C.CLI_MIDDLE_INITIAL MIDDLENAME,
      C.CLI_LAST_NAME LASTNAME,
      C.CLI_SUFFIX SUFFIX,
      C.CLI_BIRTHDAY DOB
FROM CLIENTS_AND_FACILITATORS C
WHERE LOWER(CLI_EMAIL_ADDRESS)=LOWER(:participant_email_bv)